services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: devices-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ijf2HDWCest22n5w"
    ports:
      - "1433:1433"
    volumes:
      - devices_sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'ijf2HDWCest22n5w' -Q 'SELECT 1' -b -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  devices_sqlserver_data:
